version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: gorilla-server
    volumes:
      - ./server:/server
    ports:
      - "34568:80"
